"""
Django settings for decast_aggregation_server project.

Generated by 'django-admin startproject' using Django 1.11.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

import djcelery
djcelery.setup_loader()
from kombu import Exchange, Queue

BROKER_URL = "amqp://guest:guest@localhost:5672//"
#BROKER_URL = "django://"

CELERY_DEFAULT_QUEUE = "default"
CELERY_DEFAULT_EXCHANGE_TYPE = "default"
CELERY_DEFAULT_ROUTING_KEY = "default"
CELERY_QUEUES = (
    #Queue('default', Exchange('default'), routing_key='default'),
    #Queue('test', Exchange('default'), routing_key='test'),
    Queue('sendauthreportchecker', Exchange('default'), routing_key='sendauthreportchecker'),
    #Queue('sendtestrabbitmq', Exchange('default'), routing_key='sendtestrabbitmq'),
    Queue('sendresponse', Exchange('default'), routing_key='sendresponse'),
   # Queue('sendresponse2', Exchange('default'), routing_key='sendresponse2'),
    Queue('sendgetpaybillreport', Exchange('default'), routing_key='sendgetpaybillreport'),
    Queue('sendchangepersonalaccountreport', Exchange('default'), routing_key='sendchangepersonalaccountreport'),
)
CELERY_ROUTES = {
    'server.tasks.SendAuthReportChecker': {
        'queue': 'sendauthreportchecker',
        'routing_key': 'sendauthreportchecker',
    },
    #'server.tasks.SendAuthReport': {
    #    'queue': 'default',
    #    'routing_key': 'default',
    #},
    'server.tasks.SendChangePersonalAccountReport': {
        'queue': 'sendchangepersonalaccountreport',
        'routing_key': 'sendchangepersonalaccountreport',
    },
    'server.tasks.SendGetPayBillReport': {
        'queue': 'sendgetpaybillreport',
        'routing_key': 'sendgetpaybillreport',
    },
    #'server.tasks.SendTestRabbitMQ': {
    #    'queue': 'sendtestrabbitmq',
    #    'routing_key': 'sendtestrabbitmq',
   #},
    'server.tasks.SendTestRabbitMQ2': {
      'queue': 'sendtestrabbitmq2',
      'routing_key': 'sendtestrabbitmq2',
    },
    'server.tasks.SendResponse': {
        'queue': 'sendresponse',
        'routing_key': 'sendresponse',
    },
    'server.tasks.Deliver': {
        'queue': 'test',
        'exchange': 'default',
        'routing_key': 'test',
    }
}



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'essk_ue*sh6^alnhs5*^+e@z-d@q0x15@cf$wd!^o$mtv0)$^^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'server',
    'djcelery',
    'kombu.transport.django',
]

APPS = {
    'decast_eirc' : 'ia6roza6e0q4a1rz9uxsxsmbjx0c7vv1q2o9eyd',
    'decast_billing' : 'ouu4wsiwtyuubi1pqve1fpe7ygf076tb5u',
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'decast_aggregation_server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'decast_aggregation_server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
