# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-12 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('status', models.BooleanField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChangeAccountReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('old', models.CharField(max_length=50)),
                ('new', models.CharField(max_length=50)),
                ('status', models.BooleanField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayBillReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('personal_account', models.CharField(max_length=50)),
                ('rate', models.FloatField(default=0.0)),
                ('reading', models.CharField(max_length=50)),
                ('status', models.BooleanField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
