# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('value', models.FloatField(default=0.0)),
            ],
        ),
    ]
