# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('personal_account', models.CharField(max_length=50)),
                ('sent_reading', models.IntegerField(default=0)),
                ('serial_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=50)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Device', verbose_name='\u0423\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u043e')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.User', verbose_name='\u0412\u043b\u0430\u0434\u0435\u043b\u0435\u0446 \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u0430'),
        ),
    ]
